### ISSUE TITLE
March 1, 2018 patch increased bonus heroes to 12

### ISSUE THREAD

**Issue by Serity** [victorvde/dota_bonus_heroes#1]
Still seems to match bonus.txt, but adds Juggernaut and Disruptor for today.

I'd just edit the source myself but I can't even get bonus.exe to run (throws missing tier0.dll error and crashes and then if copied from dota2 bin (tried \bin\tier0.dll, \game\bin\win32\tier0.dll and \game\bin\win64\tier0.dll) folder, just crashes without error), so I definitely can't trust myself to figure out if changing the number from 10 to 12 will actually give the correct values every day.

**Comment by victorvde** [comment]
The win64 tier0.dll should have worked. I've included the lastest versions of the dlls now.

Editing the 10 to 12 works, but I've made it a bit more complicated for historical accuracy.

Thanks.
